# Maintainer: Rui Ramos
# Maintainer: Rui Ramos <no-reply@rust-lang.org>
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=myhello-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="A HelloWorld Application for AUR testing purposes"
url="https://rramos.github.io"
license=("MIT")
arch=("x86_64")
provides=("myhello")
conflicts=("myhello")
source=("https://github.com/rramos/rust-helloworld.git/releases/download/v$pkgver/myhello-$pkgver-x86_64.tar.gz")
sha256sums=("ef8ce03c73185ef872116c17971c21f6f8f2c8f67d42a5c0b4ca876d164191b2")

package() {
    install -Dm755 myhello -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
